### ISSUE TITLE
PSQL not found during first db migration in solidtime/solidtime:latest

### ISSUE THREAD

**Issue by figachek** [solidtime-io/self-hosting-examples#4]
image: "solidtime/solidtime:${SOLIDTIME_IMAGE_TAG:-latest}"

docker compose up app
```
WARN[0000] Found orphan containers ([docker-scheduler-run-71ca7a814c5e]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Running 2/0
 ✔ Container docker-database-1  Running                                                                                                                                                            0.0s
 ✔ Container docker-app-1       Running                                                                                                                                                            0.0s
Attaching to app-1
app-1  |
app-1  |    INFO  Preparing database.
app-1  |
app-1  |   Creating migration table ..................................... 289.35ms DONE
app-1  |
app-1  |    INFO  Loading stored database schemas.
app-1  |
app-1  |   database/schema/pgsql-schema.sql ............................. 109.23ms FAIL
app-1  |
app-1  | [2024-10-14 22:58:55] production.ERROR: The command "psql --file="${:LARAVEL_LOAD_PATH}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --username="${:LARAVEL_LOAD_USER}" --dbname="${:LARAVEL_LOAD_DATABASE}"" failed.
app-1  |
app-1  | Exit Code: 127(Command not found)
app-1  |
app-1  | Working directory: /var/www/html
app-1  |
app-1  | Output:
app-1  | ================
app-1  |
app-1  |
app-1  | Error Output:
app-1  | ================
app-1  | sh: 1: psql: not found
app-1  |  {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"psql --file=\"${:LARAVEL_LOAD_PATH}\" --host=\"${:LARAVEL_LOAD_HOST}\" --port=\"${:LARAVEL_LOAD_PORT}\" --username=\"${:LARAVEL_LOAD_USER}\" --dbname=\"${:LARAVEL_LOAD_DATABASE}\"\" failed.
app-1  |
app-1  | Exit Code: 127(Command not found)
app-1  |
app-1  | Working directory: /var/www/html
app-1  |
app-1  | Output:
app-1  | ================
app-1  |
app-1  |
app-1  | Error Output:
app-1  | ================
app-1  | sh: 1: psql: not found
app-1  |  at /var/www/html/vendor/symfony/process/Process.php:269)
app-1  | [stacktrace]
app-1  | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/PostgresSchemaState.php(46): Symfony\\Component\\Process\\Process->mustRun()
app-1  | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(284): Illuminate\\Database\\Schema\\PostgresSchemaState->load()
app-1  | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(40): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
app-1  | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Factory.php(58): Illuminate\\Console\\View\\Components\\Task->render()
app-1  | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(276): Illuminate\\Console\\View\\Components\\Factory->__call()
app-1  | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(153): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->loadSchemaState()
app-1  | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(110): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
app-1  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(616): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
app-1  | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(109): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
app-1  | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(88): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->runMigrations()
app-1  | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
app-1  | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
app-1  | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
app-1  | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
app-1  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
app-1  | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
app-1  | #16 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
app-1  | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
app-1  | #18 /var/www/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
app-1  | #19 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
app-1  | #20 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
app-1  | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
app-1  | #22 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
app-1  | #23 {main}
app-1  | "}
app-1  | In Process.php line 269:
app-1  |
app-1  |   The command "psql --file="${:LARAVEL_LOAD_PATH}" --host="${:LARAVEL_LOAD_HO
app-1  |   ST}" --port="${:LARAVEL_LOAD_PORT}" --username="${:LARAVEL_LOAD_USER}" --db
app-1  |   name="${:LARAVEL_LOAD_DATABASE}"" failed.
app-1  |
app-1  |   Exit Code: 127(Command not found)
app-1  |
app-1  |   Working directory: /var/www/html
app-1  |
app-1  |   Output:
app-1  |   ================
app-1  |
app-1  |
app-1  |   Error Output:
app-1  |   ================
app-1  |   sh: 1: psql: not found
app-1  |
app-1  |
app-1 exited with code 0
app-1  |
app-1  |    INFO  Preparing database.
app-1  |
app-1  |   Creating migration table ..................................... 174.09ms DONE
app-1  |
app-1  |    INFO  Loading stored database schemas.
app-1  |
app-1  |   database/schema/pgsql-schema.sql ............................. 156.79ms FAIL
```

**Comment by korridor** [comment]
Sorry about that, we made a mistake in the build process and an old version `0.0.2` was pushed into `latest`, instead of the latest version `0.2.0`.

Please pull `latest` again and the issue should be resolved.

**Comment by figachek** [comment]
@korridor Thanks a lot, now system is up
